# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/splitDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_splitDialog(object):
    def setupUi(self, splitDialog):
        splitDialog.setObjectName("splitDialog")
        splitDialog.resize(366, 86)
        self.verticalLayout = QtWidgets.QVBoxLayout(splitDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(splitDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.splitTimeEdit = QtWidgets.QTimeEdit(splitDialog)
        self.splitTimeEdit.setEnabled(True)
        self.splitTimeEdit.setMaximumTime(QtCore.QTime(13, 0, 0))
        self.splitTimeEdit.setTime(QtCore.QTime(1, 2, 3))
        self.splitTimeEdit.setObjectName("splitTimeEdit")
        self.verticalLayout.addWidget(self.splitTimeEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(splitDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(splitDialog)
        self.buttonBox.accepted.connect(splitDialog.accept)
        self.buttonBox.rejected.connect(splitDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(splitDialog)

    def retranslateUi(self, splitDialog):
        _translate = QtCore.QCoreApplication.translate
        splitDialog.setWindowTitle(_translate("splitDialog", "split audiobook"))
        self.label.setText(_translate("splitDialog", "Split audiobook into pieces of max hh:mm:ss"))
        self.splitTimeEdit.setDisplayFormat(_translate("splitDialog", "HH:mm:ss"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    splitDialog = QtWidgets.QDialog()
    ui = Ui_splitDialog()
    ui.setupUi(splitDialog)
    splitDialog.show()
    sys.exit(app.exec_())
